### ISSUE TITLE
Import error in targeted pixel

### ISSUE THREAD

**Issue by mattngc** [raysect/source#193]
When merging two branches last night into master, we forgot to check for clashes between the branches. The targeted pixel branch was developed without the pipeline enhancements. We tested both separately but not together. This means the current master crashes due to an import error.

```
matt@matt-G74S:~/pyFusion/raysect/source$ python demos/cornell_box.py 
Traceback (most recent call last):
  File "demos/cornell_box.py", line 122, in <module>
    from raysect.optical.observer import PinholeCamera, CCDArray
  File "/home/matt/pyFusion/raysect/source/raysect/optical/observer/__init__.py", line 33, in <module>
    from .nonimaging import *
  File "/home/matt/pyFusion/raysect/source/raysect/optical/observer/nonimaging/__init__.py", line 35, in <module>
    from .targeted_pixel import TargetedPixel
  File "raysect/optical/observer/nonimaging/targeted_pixel.pyx", line 38, in init raysect.optical.observer.nonimaging.targeted_pixel (raysect/optical/observer/nonimaging/targeted_pixel.c:22883)
    from raysect.optical.observer.pipeline.spectral import SpectralRadiancePipeline0D
ImportError: cannot import name SpectralPipeline0D
```

**Comment by mattngc** [comment]
Also somehow missed the import changes in some of the demos. Need to fix this ASAP.
