### ISSUE TITLE
Make wheels available on PyPI?

### ISSUE THREAD

**Issue by jacklovell** [raysect/source#320]
Would it be possible to upload Raysect wheels to PyPI? They seem to build OK using `python setup.py bdist_wheel`, and aren't significantly larger than the tarball already on PyPI. It would significantly speed up installation for most users, and I believe it would also significantly speed up the CI builds on Cherab.

**Comment by CnlPepper** [comment]
I've built and uploaded manylinux1 wheels for python 3.6 and 3.7 for the latest release. Could you ry using them with a basic `pip install raysect`?

Took a bit of faffing around to get these built, but it seems to be working here. We should be able to use the same approach for Cherab if this works. I'll need to built a script to automate it, I did it manually this time.

**Comment by jacklovell** [comment]
The install seemed to go OK, in a clean conda environment on Python 3.7:
```
[jovell@cmodws79 ~]$ pip install raysect
Collecting raysect
  Downloading https://files.pythonhosted.org/packages/19/61/f250819d184ea34ad6545847190c438edc314eff85f9318e33ee2617f665/raysect-0.6.0-cp37-cp37m-manylinux1_x86_64.whl (38.9MB)
     |████████████████████████████████| 38.9MB 1.2MB/s 
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/9b/af/4fc72f9d38e43b092e91e5b8cb9956d25b2e3ff8c75aed95df5569e4734e/numpy-1.17.4-cp37-cp37m-manylinux1_x86_64.whl (20.0MB)
     |████████████████████████████████| 20.0MB 20.4MB/s 
Collecting cython>=0.28
  Downloading https://files.pythonhosted.org/packages/d8/58/2deb24de3c10cc4c0f09639b46f4f4b50059f0fdc785128a57dd9fdce026/Cython-0.29.14-cp37-cp37m-manylinux1_x86_64.whl (2.1MB)
     |████████████████████████████████| 2.1MB 18.7MB/s 
Installing collected packages: numpy, cython, raysect
Successfully installed cython-0.29.14 numpy-1.17.4 raysect-0.6.0
```
I'm not sure Cython is necessary if the package is already built. Also, matplotlib wasn't pulled in, which should be a dependency of raysect. I noticed this when I tried to run one of the demos, and the pipeline rendering failed.

Finally, I tried runing the unit tests, and it seems one of them errors out:
```
[jovell@cmodws79 ~]$ python -m unittest discover -s ~/scratch/anaconda3/envs/raysect-wheel-test/lib/python3.7/site-packages/raysect
.............................................................................................................................................................................................................................................................................................................................................................E
======================================================================
ERROR: optical.observer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: optical.observer
Traceback (most recent call last):
  File "/home/jovell/scratch/anaconda3/envs/raysect-wheel-test/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/home/jovell/scratch/anaconda3/envs/raysect-wheel-test/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/jovell/scratch/anaconda3/envs/raysect-wheel-test/lib/python3.7/site-packages/raysect/optical/observer/__init__.py", line 32, in <module>
    from .imaging import *
  File "/home/jovell/scratch/anaconda3/envs/raysect-wheel-test/lib/python3.7/site-packages/raysect/optical/observer/imaging/__init__.py", line 39, in <module>
    from .opencv import OpenCVCamera
  File "raysect/optical/observer/imaging/opencv.pyx", line 41, in init raysect.optical.observer.imaging.opencv
AttributeError: type object 'raysect.optical.observer.imaging.opencv.OpenCVCame' has no attribute '__reduce_cython__'


----------------------------------------------------------------------
Ran 350 tests in 0.043s

FAILED (errors=1)
```
I haven't seen this error before. Also, it's rather curiously running 350 tests, despite the last build on Github running 349. Perhaps there is something wrong in the way I'm getting unittest to discover and run the tests...

**Comment by CnlPepper** [comment]
Thanks for testing that, glad it worked.

I suspect you have opencv installed, so it is running an additional test. I'll have to modify the CI to include opencv to trigger that test.

The cython dependency is necessary for the source distribution at the moment, so it gets installed as a side effect. You are right about the matplotlib dependency. I'm not sure why that is missing. I'll fix that in the next point release.

**Comment by jacklovell** [comment]
It doesn't look like I have opencv installed:
```
[jovell@cmodws79 ~]$ pip list
Package         Version            
--------------- -------------------
certifi         2019.9.11          
cycler          0.10.0             
Cython          0.29.14            
idlbridge       1.1.1              
kiwisolver      1.1.0              
matplotlib      3.1.1              
MDSplus         7.91.0             
numpy           1.17.4             
pip             19.3.1             
pyparsing       2.4.5              
python-dateutil 2.8.1              
raysect         0.6.0              
setuptools      41.6.0.post20191030
six             1.13.0             
wheel           0.33.6 
```
(Ignore idlbridge, that came from a `pip install --user`). And I installed matplotlib manually.

**Comment by jacklovell** [comment]
By the way, using the raysect wheels speeds up the Cherab core CI checks by about 9 minutes, a factor of 3.

**Comment by mattngc** [comment]
This has been done by @CnlPepper.
